### ISSUE TITLE
Could I close the pmc notice?

### ISSUE THREAD

**Issue by AdamPengG** [StephLin/KCP#3]
HI Lin, the program always print the debug info
"*** [pmc: thread 3]   current max clique = 154,  time = 0.0690331 sec
DEBUG current mc: 154
DEBUG current mc: 154
DEBUG current mc: 154
DEBUG current mc: 154"
Could I close it and what should I do?

**Comment by StephLin** [comment]
Hi Adam,

Those debug messages "DEBUG current mc: 154 ..." come from [a fork of pmc](https://github.com/jingnanshi/pmc) that is used in [TEASER++](https://github.com/MIT-SPARK/TEASER-plusplus).

https://github.com/jingnanshi/pmc/blob/de9fdaa1/pmcx_maxclique.cpp#L224

The pmc code should be located at `TEASER-plusplus/build/pmc-src` in your machine. You can remove them manually and then reinstall **TEASER++**.

BTW, It's fine of me to add a new option in KCP to mute all debug messages so that you don't have to *hack* it manually, but it will also mute other messages such as "Translation estimation complete."

**Comment by StephLin** [comment]
I suppose that the issue is resolved. Feel free to re-open it if you have other concerns. Thanks!
